Mount pacman private-keys-v1 as tmpfs
QubesOS/qubes-builder-archlinux pull request #45
Opened 2020-11-30 16:50 UTC by ejose19

As mentioned by @DemiMarie on [qubes-issues](https://github.com/QubesOS/qubes-issues/issues/6242), this should prevent a compromised AppVM to sign packages that the TemplateVM will trust (by mounting that folder as tmpfs on both builder and template).

2020-11-30 18:57 UTC, DemiMarie requested changes
We need to move the `pacman-key --init` and `pacman-key --populate` calls into a single call to `scripts/arch-chroot-lite`, so that `pacman-key --populate` has access to the signing key.

2020-11-30 18:57 UTC, DemiMarie commented on scripts/arch-chroot-lite
> +    chroot_add_mount pacman-privkeys "$1/etc/pacman.d/gnupg/private-keys-v1.d" -t tmpfs -o mode=600,nosuid,noexec
```suggestion
    chroot_add_mount pacman-privkeys "$1/etc/pacman.d/gnupg/private-keys-v1.d" -t tmpfs -o mode=600,nosuid,noexec,nodev ||
    exit
```

We need to exit if the mount fails for any reason.

2020-11-30 18:57 UTC, DemiMarie commented on scripts/04_install_qubes.sh
> +tmpfs                   /etc/pacman.d/gnupg/private-keys-v1.d       tmpfs   defaults,noexec,mode=600    0 0
```suggestion
tmpfs                   /etc/pacman.d/gnupg/private-keys-v1.d       tmpfs   defaults,noexec,nosuid,nodev,mode=600    0 0
```

2020-11-30 21:16 UTC, ejose19 commented
Ok, should be good now. Thanks for the review

2020-12-01 02:48 UTC, DemiMarie commented
@marmarek can you merge this?

2020-12-01 06:05 UTC, marmarek approved these changes
This will break adding extra keys - like in #42 (archlinux.qubes-os.org repo), but we can fix it there.
Thanks @ejose19

2020-12-01 06:06 UTC, merged