refactor: improve mirrorlist mechanism
QubesOS/qubes-builder-archlinux pull request #55
Opened 2021-01-28 00:23 UTC by ejose19

This PR addresses 2 things:

- Move defaults to Makefile.archlinux (before ARCHLINUX_MIRROR on Makefile.archlinux was replacing defaults set in prepare-chroot-base)
- Use a file instead of mirror string envs separated by comma and sed'ing into mirrorlist.dist, this method is way more clean and direct, also it's more ergonomic for users in case they want to specify a long list of servers.

2021-01-28 02:16 UTC, ejose19 commented
Also, I've noticed builds errors out a lot with 404 on servers, so maybe we should increase the default servers even if they're not worldwide (users will prefer some packages to be downloaded slowly than failing the entire build). If agree I will update the mirrorlist with 10-20 mirrors.

2021-02-15 23:57 UTC, marmarek requested changes
Besides technical comments below, I'm not sure if using a variable pointing at a separate file is really an improvement. This means if you copy your builder.conf elsewhere, it won't work (unless you left the default, in which case the setting isn't really useful). This is the case for [building the template in DisposableVM](https://github.com/QubesOS/qubes-builder/blob/master/doc/TemplateDispVMBuild.md) for example.

The code for sed-ing mirrorlist file indeed wasn't pretty, but I'd prefer to keep the actual setting directly in builder.conf. Maybe the variable should contain the full path (possibly without `$repo/os/$arch` to avoid the need to escape the dollar sign) and have mirrorlist constructed from it directly, instead of using mirrorlist.dist as a source? Something like:
```bash
for MIRROR_ENTRY in "${ARCHLINUX_MIRROR[@]}"; do
    echo "Server = $MIRROR_ENTRY/\$repo/os/\$arch"
done > "${BOOTSTRAP_DIR}/etc/pacman.d/mirrorlist"
```

2021-02-15 23:57 UTC, marmarek commented on prepare-chroot-base
> +cat "$ARCHLINUX_MIRRORLIST_FILE" > "${CACHEDIR}/bootstrap/etc/pacman.d/mirrorlist"
While at it, use `$BOOTSTRAP_DIR` like in other places here.

2021-02-15 23:57 UTC, marmarek commented on scripts/mirrorlist
> +Server = http://mirrors.evowise.com/archlinux/$repo/os/$arch
While at it, maybe add https://mirrors.edge.kernel.org/archlinux/? It is tier 1 contrary to evowise.com.

2021-02-16 17:34 UTC, ejose19 commented
Originally I wanted to use the output of ```cat mirrorlist``` into the variable directly, as making users strip ```Server = ... /$repo/os/$arch``` only to be placed again by the script is a bit "wasteful", however seems like this 
https://github.com/QubesOS/qubes-linux-template-builder/blob/4d8c03b9a88693fb74435d8d3dde09ea02641bb7/Makefile#L65-L68
doesn't support variables with newlines, preventing the desired solution.

I applied the PR with some comments:
- Removed ARCHLINUX_MIRROR default from Makefile, as readability is way better in shell syntax when having many mirrors.
- The output of "Setting pacman mirrorlist as:" now print each mirror in a separate line, improving readability as well.
- Use https only for default mirrors, since there was a previous vulnerability (https://github.com/QubesOS/qubes-issues/issues/6242), there shouldn't be any http mirror making any mitm attack easier.

2021-03-23 16:25 UTC, ejose19 commented
@marmarek is there something left to be done or it can be merged?

2021-08-26 20:22 UTC, ejose19 commented
Friendly ping @marmarek

2022-01-06 04:22 UTC, marmarek commented
PipelineRetry

2022-01-06 13:02 UTC, marmarek commented
@ejose19 we (finally!) have CI for Arch working again, [recent run on the master branch succeeded](https://gitlab.com/QubesOS/qubes-builder-archlinux/-/pipelines/442398954), but with this PR it fails. It gets 404 on accessing ftp.halifax.rwth-aachen.de (qubes repo mirror), but I don't see why your changes would cause that. Maybe some mirrorlist file formatting issue?

2022-01-06 15:50 UTC, ejose19 commented
As seen in the [logs ](https://storage.googleapis.com/gitlab-gprd-artifacts/7d/e3/7de34c2a749c385fcc17431adc64a256b5a34e54289f4323a0de5a559805852f/2022_01_06/1946402849/2111005655/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=Xhg1%2FkGtvzsEACwfICUoXNGiKGo5VgDvS4iIHcejw1uL6wX3GU2meYwT%2FdO7%0AyXT3kdvoZFtE2cRBnOxIv%2Fe7g98G6B2i83477FMUr18PUR9cKeGUCvrOjDN1%0ADCYQxjCW2uRE0KR7VdaOhLPz6OovfyF2UKp5ikOrMIt%2FoAs1CKsZC5ymc5qm%0Aji2WDXcoyfhLgra6rATITmzyCu4GIwhDq7Pz%2F0oF%2B720E9MxMjxqozxuJMfI%0Arvd0ETjOBHYv%2BFkoE8rtirPnzum%2FoisGhkkVZK7ZzI%2FvtoTPvMeFt3g93nIK%0AKPd03Nwq2vFz2FYtFl%2Bd%2B%2BwSxlfII4daTXk4FMF4Bw%3D%3D&Expires=1641484008), I see that only this mirror is set (`https://ftp.halifax.rwth-aachen.de`), that mirror only expose `qubes` repo, no `core`, `extra`, ect, so that's why it gives 404 when querying `core.db`

```
 --> Setting pacman mirrorlist as:
https://ftp.halifax.rwth-aachen.de
```

```
error: failed retrieving file 'core.db' from ftp.halifax.rwth-aachen.de : The requested URL returned error: 404
```

the solution I see to make this simpler, is to add another env `APPEND_ARCHLINUX_MIRROR`, and then merge both variables before creating the mirrorlist, that way, when specifying only a subset of all available repositories through `ARCHLINUX_MIRROR` it doesn't unintentionally overwrite the defaults (pipeline would need to use this env, but I don't see where it's being set)

2022-01-06 16:20 UTC, marmarek commented
Do you see why this mirror is set? While it is indeed one of the mirrors for qubes repo, I can't find where `ARCHLINUX_MIRROR` is pointed at it.

2022-01-06 18:26 UTC, ejose19 commented
I've checked all repositories under github `QubesOS` org and couldn't find anything relevant:

```yaml
$ rg --no-ignore --hidden -i -F "halifax"

qubesos.github.io/_data/downloads-mirrors.yml
52:  org_url: https://www.halifax.rwth-aachen.de
55:  - url: http://ftp.halifax.rwth-aachen.de/qubes/iso/

qubesos.github.io/_data/downloads.yml
47:      - name: halifax.rwth-aachen.de
53:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.iso
55:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.iso.DIGESTS
56:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.iso.asc
69:      - name: halifax.rwth-aachen.de
75:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.torrent
77:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.iso.DIGESTS
78:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.1.0-rc3-x86_64.iso.asc
132:      - name: halifax.rwth-aachen.de
138:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.iso
140:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.iso.DIGESTS
141:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.iso.asc
154:      - name: halifax.rwth-aachen.de
160:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.torrent
162:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.iso.DIGESTS
163:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R4.0.4-x86_64.iso.asc
195:      - name: halifax.rwth-aachen.de
201:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.iso
203:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.iso.DIGESTS
204:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.iso.asc
228:      - name: halifax.rwth-aachen.de
234:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.torrent
236:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.iso.DIGESTS
237:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.2.1-x86_64.iso.asc
281:      - name: halifax.rwth-aachen.de
287:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.iso
289:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.iso.DIGESTS
290:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.iso.asc
314:      - name: halifax.rwth-aachen.de
320:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.torrent
322:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.iso.DIGESTS
323:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-x86_64.iso.asc
372:      - name: halifax.rwth-aachen.de
378:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-alpha1.1-x86_64.iso
380:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-alpha1.1-x86_64.iso.DIGESTS
381:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.1-alpha1.1-x86_64.iso.asc
414:      - name: halifax.rwth-aachen.de
420:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.0-x86_64-DVD.iso
422:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.0-x86_64-DVD.iso.DIGESTS
423:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R3.0-x86_64-DVD.iso.asc
468:      - name: halifax.rwth-aachen.de
474:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R2-x86_64-DVD.iso
476:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R2-x86_64-DVD.iso.DIGESTS
477:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R2-x86_64-DVD.iso.asc
515:      - name: halifax.rwth-aachen.de
521:        url: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R1-x86_64-DVD.iso
523:          hash: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R1-x86_64-DVD.iso.DIGESTS
524:          sig: http://ftp.halifax.rwth-aachen.de/qubes/iso/Qubes-R1-x86_64-DVD.iso.asc

build-logs-secondary/build-archlinux/log_2022-01-05_23-02-49
426:2022-01-05 23:02:49.608456 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
427:2022-01-05 23:02:49.608467 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1095:2022-01-05 23:02:49.615565 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1096:2022-01-05 23:02:49.615576 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1762:2022-01-05 23:02:49.622715 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1763:2022-01-05 23:02:49.622726 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch

build-logs-secondary/build-archlinux/log_2022-01-05_23-02-13
426:2022-01-05 23:02:13.505189 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
427:2022-01-05 23:02:13.505200 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1095:2022-01-05 23:02:13.511890 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1096:2022-01-05 23:02:13.511901 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1762:2022-01-05 23:02:13.518785 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1763:2022-01-05 23:02:13.518796 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch

build-logs-secondary/build-archlinux/log_2022-01-05_18-22-59
426:2022-01-05 18:22:59.866978 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
427:2022-01-05 18:22:59.866989 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1095:2022-01-05 18:22:59.884852 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1096:2022-01-05 18:22:59.884863 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1762:2022-01-05 18:22:59.894105 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1763:2022-01-05 18:22:59.894116 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch

build-logs-secondary/build-archlinux/log_2022-01-06_00-02-46
426:2022-01-06 00:02:46.649816 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
427:2022-01-06 00:02:46.649828 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1095:2022-01-06 00:02:46.657548 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1096:2022-01-06 00:02:46.657559 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1762:2022-01-06 00:02:46.664442 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
1763:2022-01-06 00:02:46.664453 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch

build-logs-secondary/build-archlinux/log_2022-01-05_23-07-04
3936:2022-01-05 23:18:31.743279 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
3937:2022-01-05 23:18:31.743290 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
4738:2022-01-05 23:18:31.751749 +0000 build-archlinux: #Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
4739:2022-01-05 23:18:31.751761 +0000 build-archlinux: #Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
5538:2022-01-05 23:18:31.759914 +0000 build-archlinux: #Server = http:// [...]

2022-01-10 22:25 UTC, ejose19 commented
I'm pretty sure that variable is set at gitlab pipeline config, but since the display of such env is not implemented yet (https://gitlab.com/gitlab-org/gitlab/-/issues/22204), it's only an assumption. @marmarek can you trigger another pipeline run?

2022-01-11 02:52 UTC, marmarek commented
> I'm pretty sure that variable is set at gitlab pipeline config

You are absolutely right! It is indeed set there. Cleared it now.

2022-01-11 02:52 UTC, marmarek commented
PipelineRetry

2022-01-11 15:03 UTC, ejose19 commented
Seems CI is all green now

2022-07-14 22:23 UTC, marmarek approved these changes

2022-07-14 22:23 UTC, merged